BlackMarketAuctionPart3/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlackMarketAuctionPart3.Models;

/*
     AuctionController.cs
     Austin Cameron - Patrick Ross - Ryan Jameson
     Black Market Auction House
     This is the auction list controller
*/

namespace BlackMarketAuctionPart3.Controllers
{
    public class AuctionController : Controller
    {
        private AuctionContext AuctionDB = new AuctionContext();

        // GET: Menu
        public ActionResult Index()
        {
            List<Category> categories = AuctionDB.Categories.ToList();
            return View(categories);
        }

        // GET: Menu/Details/5
        public ActionResult Browse(string categories = "Mounts")
        {
            // Retrieve the Category and its Associated items from database
            Category categoryModel = AuctionDB.Categories.Include("Items").Single(g => g.Name == categories);

            return View(categoryModel);
        }
        public ActionResult Details(int id = 1)
        {
            Item item = AuctionDB.Items.Find(id);

            return View(item);
        }

    }
}

BlackMarketAuctionPart3/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlackMarketAuctionPart3.Models;
using BlackMarketAuctionPart3.ViewModels;

/*
     ShoppingCartController.cs
     Austin Cameron - Patrick Ross - Ryan Jameson
     Black Market Auction House
     This is the shopping cart controller

*/

namespace BlackMarketAuctionPart3.Controllers
{
    public class ShoppingCartController : Controller
    {
        AuctionContext auctionDB = new AuctionContext();

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                OrderItemList = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the item from the database
            var addedItem = auctionDB.Items
                .Single(item => item.ItemID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the item to display confirmation
            string itemName = auctionDB.OrderItems
                .Single(item => item.RecordID == id).Item.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteID = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

BlackMarketAuctionPart3/Views/Auction/Browse.cshtml
@using BlackMarketAuctionPart3.Models
@model Category

<!--
     Browse.cshtml
     Austin Cameron - Patrick Ross - Ryan Jameson
     Black Market Auction House
     This is the browse view for the auction list
-->

@helper Truncate(string input, int length)
{
if (input.Length <= length)
{
@input
}
else
{
@input.Substring(0, length)<text>...</text>
}
}

@{
    ViewBag.Title = "Browse";
}
<div>
    <h2>Browsing Category: @Model.Name</h2>
    @foreach (Item item in Model.items)
    {
        <div class="thumb1">
            <div class="col-sm-3 col-md-4">
                <div class="thumbnail">
                    <img src="@item.ItemImage" alt="@item.Name" width="256" height="256">
                    <div class="caption">
                        <div class="color1">
                            <h3>@item.Name</h3>
                            <p>@item.Category.Name</p>
                            <p>$@item.Price</p>
                        </div>
                        <div class="Button--ghost">
                            <a href="@Url.Action("Index")" class="Button" title="Back"><i class="fa fa-chevron-left"> Back</i></a>
                            <a href="@Url.Action("Details", new { id = item.ItemID })" class="Button" title="View Category">View Item</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

BlackMarketAuctionPart3/Views/Auction/Details.cshtml
@using BlackMarketAuctionPart3.Models
@model Item

    <!--
         Details.cshtml
         Austin Cameron - Patrick Ross - Ryan Jameson
         Black Market Auction House
         This is the detailed view for an item on the auction list
    -->

@{
    ViewBag.Title = "Details";
}
<br />
<div class="itemcat1">
    <h1>@Model.Name</h1>
    <h3>@Model.Category.Name</h3>
</div>
<div class="thumb2">
    <div class="col-sm-3 col-md-6">
        <div class="thumbnail text-center" >
            <img src="@Model.ItemImage" alt="@Model.Name" />
            <div class="color1">
                <h3>@Model.Description</h3>
                <h4><a href="@Model.ItemLink">Wowhead Link</a></h4>
                <h3>$@Model.Price</h3>
            </div>
            <a href="@Url.Action("Browse", new { categories = Model.Category.Name })" class="Button" title="Back"><i class="fa fa-chevron-left"> Back</i></a>
            <a href="@Url.Action("addToCart", "ShoppingCart", new { id = Model.ItemID })" class="Button" title="Purchase"><i class="fa fa-shopping-cart"> Add to Cart</i></a>
        </div>
    </div>
</div>
    <div class="text-center">
       
    </div>

BlackMarketAuctionPart3/Views/Auction/Index.cshtml
@using BlackMarketAuctionPart3.Models
@model IEnumerable<Category>

    <!--
         Index.cshtml
         Austin Cameron - Patrick Ross - Ryan Jameson
         Black Market Auction House
         This is the index view for the auction list
    -->


@{
    ViewBag.Title = "Index";
}

<h2>Browse Categories</h2>
<p>
    Select from one of the @Model.Count() categories:
</p>
    @foreach (Category item in Model)
    {
        <div class="thumb1">
      
                <div class="col-sm-3 col-md-3">
                    <div class="thumbnail">
                        <img src="@item.ThumbnailImage" alt="@item.Name" width="256" height="256">
                        <div class="caption">
                            <div class="color1">
                                <h3>@item.Name</h3>
                                <p>@item.Description</p>
                            </div>
                            <p class="text-center"><a href="@Url.Action("Browse", new { categories = item.Name })" class="Button" title="View Category">View</a></p>
                        </div>
                    </div>
                </div>
            </div>
    }