BlackMarketAuctionPart3/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlackMarketAuctionPart3.Models;

/*
     AuctionController.cs
     Austin Cameron - Patrick Ross - Ryan Jameson
     Black Market Auction House
     This is the auction list controller
*/

namespace BlackMarketAuctionPart3.Controllers
{
    public class AuctionController : Controller
    {
        private AuctionContext AuctionDB = new AuctionContext();

        // GET: Menu
        public ActionResult Index()
        {
            List<Category> categories = AuctionDB.Categories.ToList();
            return View(categories);
        }

        // GET: Menu/Details/5
        public ActionResult Browse(string categories = "Mounts")
        {
            // Retrieve the Category and its Associated items from database
            Category categoryModel = AuctionDB.Categories.Include("Items").Single(g => g.Name == categories);

            return View(categoryModel);
        }
        public ActionResult Details(int id = 1)
        {
            Item item = AuctionDB.Items.Find(id);

            return View(item);
        }

    }
}

BlackMarketAuctionPart3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<!--
     _Layout.cshtml
     Austin Cameron - Patrick Ross - Ryan Jameson
     Black Market Auction House
     This is the layout page for the Black Market Auction House
-->

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Black Market Auctions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index", "Home")" class="navbar-brand">Black Market Auctions</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li title="Home Page">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li title="Store Page">@Html.ActionLink("Store", "Index", "Auction")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>

            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
                    <footer class="footer">
                        <p>&copy; @DateTime.Now.Year - Black Market Auction House  ||   @Html.ActionLink("Contact", "Contact", "Home", htmlAttributes: new { title = "Contact us Here!" })  ||  @Html.ActionLink("About", "About", "Home", htmlAttributes: new { title = "Learn More About Us!" })</p>
                    </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/shoppingCart")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>